## Coding the Perceptron Algorithm

Recall that the perceptron step works as follows. 
- For a point with coordinates (p,q), label y, 
- and prediction given by the equation 
$$\hat{y} = step(w_1x_1 + w_2x_2 + b)$$ 

1. If the point is correctly classified, do nothing.
2. If the point is classified positive, but it has a negative label, subtract $$\alpha p, \alpha q,αp,αq, \ and \ \alphaα \ from \   w_1, w_2,w
1
​	 ,w 
2
​	 , and \ b \ respectively.$$
3. If the point is classified negative, but it has a positive label, add $$\alpha p, \alpha q,αp,αq, \ and \ \alphaα \ from \   w_1, w_2,w
1
​	 ,w 
2
​	 , and \ b \ respectively.$$

It'll actually draw a set of dotted lines, that show how the algorithm approaches to the best solution, given by the black solid line.

Feel free to play with the parameters of the algorithm (number of epochs, learning rate, and even the randomizing of the initial parameters) to see how your initial conditions can affect the solution!

In [17]:
import numpy as np
# Setting the random seed, feel free to change it and see different solutions.
np.random.seed(42)

In [18]:
def stepFunction(t):
    if t >= 0:
        return 1
    return 0

In [19]:
def prediction(X, W, b):
    return stepFunction((np.matmul(X,W)+b)[0])

####  Explain `trainPerceptronAlgorithm(X, y)`

`trainPerceptronAlgorithm` will randomnly generate the Weights and the bias and than optimize the line:
1. `W = np.array(np.random.rand(2,1))`
2. `b = np.random.rand(1)[0] + x_max`
3. `x_max = max(X.T[0])`, the maximum value `[ 0.78051 , -0.063669]`
4. for the number of epochs it will optimize the line

In [20]:
# TODO: Fill in the code below to implement the perceptron trick.
# The function should receive as inputs the data X, the labels y,
# the weights W (as an array), and the bias b,
# update the weights and bias W, b, according to the perceptron algorithm,
# and return W and b.
def perceptronStep(X, y, W, b, learn_rate = 0.01):
    for i in range(len(X)):
        y_hat = prediction(X[i],W,b)
        if y[i]-y_hat == 1:
            W[0] += X[i][0]*learn_rate
            W[1] += X[i][1]*learn_rate
            b += learn_rate
        elif y[i]-y_hat == -1:
            W[0] -= X[i][0]*learn_rate
            W[1] -= X[i][1]*learn_rate
            b -= learn_rate
    return W, b

In [21]:
# This function runs the perceptron algorithm repeatedly on the dataset,
# and returns a few of the boundary lines obtained in the iterations,
# for plotting purposes.
# Feel free to play with the learning rate and the num_epochs,
# and see your results plotted below.
def trainPerceptronAlgorithm(X, y, learn_rate = 0.01, num_epochs = 25):
    x_min, x_max = min(X.T[0]), max(X.T[0])
    y_min, y_max = min(X.T[1]), max(X.T[1])
    W = np.array(np.random.rand(2,1))
    b = np.random.rand(1)[0] + x_max
    # These are the solution lines that get plotted below.
    boundary_lines = []
    for i in range(num_epochs):
        # In each epoch, we apply the perceptron step.
        W, b = perceptronStep(X, y, W, b, learn_rate)
        boundary_lines.append((-W[0]/W[1], -b/W[1]))
    return boundary_lines

In [22]:
data_points = np.genfromtxt('data.csv', delimiter=',')
data_points = np.array([data_points])
data_points[0,:3,:]

array([[ 0.78051 , -0.063669,  1.      ],
       [ 0.28774 ,  0.29139 ,  1.      ],
       [ 0.40714 ,  0.17878 ,  1.      ]])

In [23]:
data_points.shape

(1, 100, 3)

In [24]:
# the data X, inputs X1, X2 For a point with coordinates (x1,x2), label y
# get the transpose of the data
X = data_points[0, :, [0, 1]].T
len(X)

100

In [25]:
X[1]

array([0.28774, 0.29139])

In [26]:
X[0]

array([ 0.78051 , -0.063669])

In [27]:
min(X.T[0]), max(X.T[0]), min(X.T[1]), max(X.T[1])

(0.0084492, 1.0, -0.063669, 1.0)

In [28]:
y = data_points[0, :, 2]
len(y)

100

In [29]:
W = np.array(np.random.rand(2))
len(W)

2

In [30]:
trained = trainPerceptronAlgorithm(X, y)
trained

[(array([-1.56110426]), array([-2.63299426])),
 (array([0.45752748]), array([1.55470892])),
 (array([-0.10086075]), array([0.41573526])),
 (array([-0.16602821]), array([0.42103506])),
 (array([-0.19634015]), array([0.51029731])),
 (array([-0.24345226]), array([0.52298673])),
 (array([-0.29296716]), array([0.53632335])),
 (array([-0.34292209]), array([0.54849516])),
 (array([-0.39519712]), array([0.56123228])),
 (array([-0.43231575]), array([0.57076701])),
 (array([-0.45476963]), array([0.57722415])),
 (array([-0.45659621]), array([0.57213908])),
 (array([-0.45793699]), array([0.66894133])),
 (array([-0.46960191]), array([0.66977523])),
 (array([-0.48129595]), array([0.67061121])),
 (array([-0.49301922]), array([0.67144929])),
 (array([-0.50477183]), array([0.67228946])),
 (array([-0.55086766]), array([0.68325529])),
 (array([-0.61734915]), array([0.70345164])),
 (array([-0.65473543]), array([0.71798984])),
 (array([-0.69369965]), array([0.73314164])),
 (array([-0.73434384]), array([0.7

In [31]:
len(trained)

25

In [37]:
(y == 1).mean()

0.5